CREATE TABLE "Anime" (
	"ID"	INTEGER,
	"Name"	TEXT NOT NULL,
	"Autor"	TEXT NOT NULL,
	"Estudio"	TEXT NOT NULL,
	"Genero"	TEXT NOT NULL,
	"Data"	TEXT NOT NULL,
	"Nota"	REAL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);