CREATE TABLE IF NOT EXISTS Animes (
	"Id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT NOT NULL,
	"Autor"	TEXT NOT NULL,
	"Estudio"	TEXT NOT NULL,
	"Genero"	TEXT NOT NULL,
	"Data"	TEXT NOT NULL,
	"Nota"	REAL
);

